name: Deploy Xnime

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  web-dev-sync:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3

      - name: ðŸ‘‰ Use PHP 8.3
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'

      - name: ðŸ™ Create env file
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env
          
      - name: ðŸ”¨ Build Composer
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
      
      - name: ðŸ”‘ Generate Laravel Key
        run: |
          php artisan key:generate

      - name: ðŸ”Œ Prepare Files for Public
        run: |
          cp -rf public/* .
          rm index.php
          mv public.php index.php

      - name: ðŸ’¾ Give Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ${{ secrets.FTP_PROTOCOL }}
          port: ${{ secrets.FTP_PORT }}
          exclude: |
            **/.git/**
            **/.github/**
            **/node_modules/**